<div class="menu-principal">
 {{widget type="interface/widget_menu" template="interface/widgets/menu.phtml" identificador="all_categories" exibicao="normal" exibir_todos_departamentos="1" texto_todos_departamentos="<svg class='icon'><use xlink:href='#menu-icon' /></svg>" ajustar_largura="1" niveis="1" ocultar_categorias="5,6,7,8,9,10,11"}}
  <div class="item categories dropdown">
    <span class="text">
      Escolha por
      <strong>Categoria</strong>
    </span>
    <div class="dropdown-content">
	{{widget type="interface/widget_menu" template="interface/widgets/menu.phtml" identificador="categories_dropdown" exibicao="vertical" texto_todos_departamentos="Todos os Departamentos" niveis="1"}}
    </div>
  </div>
  <div class="item goals dropdown">
    <span class="text">
      Escolha por
      <strong>Objetivo</strong>
    </span>
    <div class="dropdown-content">
      {{widget type="menubuilder/output" id="8" template="menubuilder/output.phtml"}}
    </div>
  </div>
  <div class="item brands dropdown">
    <span class="text">
      Escolha por
      <strong>Marcas</strong>
    </span>
    <div class="dropdown-content">
      {{widget type="shopbybrand/widget" template="shopbybrand/widget.phtml" identificador="brands-menu" exibicao="lista" markup="<a href='{[link_marca]}' title='{[nome_marca]}'> <span class='marca_imagem'>{[imagem_marca tamanho='100x100']}</span> <span class='marca_nome'>{[nome_marca]}</span></a>"}}
    </div>
  </div>
  {{widget type="interface/widget_buscaavancada" template="interface/widgets/buscaavancada.phtml" identificador="filter_menu" label_botao="Ok" atributos="1,2"}}
</div>
